version: '3'
services:
    backend:
        build: ./backend
        ports:
            - "3000:5000"
    frontend:
        build: ./frontend
        ports:
            - "80:80"
            - "443:433"
        depends_on:
            - backend
        volumes:
            - ./frontend/dist:/var/www/html
            - ./deploy/default.conf:/etc/nginx/sites-available/default
        